### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.applicationcontrol#9]
I'd like to cut a new release of this package, but I lack the PyPI privileges.

@mgedmin @jamadden You have the necessary PyPI rights, could you please share them with me (`icemac`)?

**Comment by icemac** [comment]
@mgedmin @jamadden Ping regarding release rights for https://pypi.org/project/zope.applicationcontrol/.

**Comment by icemac** [comment]
@tseaver Could you please give me (`icemac`) PyPI release rights for https://pypi.org/project/zope.applicationcontrol/?

**Comment by tseaver** [comment]
@icemac Done.

**Comment by icemac** [comment]
@tseaver Thank you!
